# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Examples\Api\Http\:
      resource: '%kernel.project_dir%/src/Api/Http/*'
      
    Shrikeh\ApiContext\Http\EventListener\Psr7Response:
      tags: [ 'kernel.event_listener' ]

    _instanceof:
      Shrikeh\ApiContext\Http\Action:
        tags:
          - 'controller.service_arguments'
      Shrikeh\App\Query\QueryHandler:
        tags:
          - { name: messenger.message_handler, bus: 'query.bus' }
      Shrikeh\App\Command\CommandHandler:
        tags:
          - { name: messenger.message_handler, bus: 'command.bus' }

    Examples\App\:
        resource: '%kernel.project_dir%/src/App'
        
    Examples\PetStore:
      resource: '%kernel.project_dir%/src/PetStore'  
    

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
